# History HIST_STAMPS="mm/dd/yyyy"
HISTSIZE=10000
SAVEHIST=8500

# Autoupdate
export UPDATE_ZSH_DAYS=5

# Antigen to manage zsh stuff
source ${HOME}/.antigen/antigen.zsh
source ${HOME}/.aliases.zsh
source ${HOME}/.env.zsh
source ${HOME}/.keys.zsh
source ${HOME}/.plugins.zsh

setopt nocorrectall
